sudo: false
language: ruby
rvm: 2.6.3
before_install: gem install bundler -v 1.16.1
if: (branch = master OR type = pull_request)

script:
  - bundle exec rake

notifications:
  slack: dius:IsS5yC3wpeTCL0rp0YY1Bmwp
  slack: bresicwhitney:7BLvxaeIoatRfxj676QPkyFP
